[package]
name = "wasmd-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.5"
serde = "1.0.151"
serde_json = "1.0.91"
tonic = "0.8.3"
